import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/classnames";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { lang } = { lang: "en" };

  return (
    <html lang={lang}>
      <body className={cn("bg-gray-200 antialiased")}>{children}</body>
    </html>
  );
}
